name: artifacts
on: workflow_dispatch

jobs:
  job_1:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: create local file
        run: |
          echo "hello world" > file.txt
      - name: use artifact
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
  
  job_2:
    name: download artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: file
          path: file.txt
      - name: show file
        run: |
          cat file.txt