name: Hello World

on:
  # triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    # this will ignore pushes to feature 
    branches-ignore:
      - 'feature/*'
    # path will only trigger the workflow when the changes are in the README.md or docs folder
    paths:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

  # allows manual execution through actions tab
  workflow_dispatch:

  # triggers the workflow on a schedule
  # schedule:
  #   # cron syntax
  #   - cron: '0 0 * * *'
  
# A workflow is made up of one or more jobs running sequentially or in parallel
jobs:
  # the name of the job
  build-app:
    # the type of runner that will execute the job
    runs-on: ubuntu-latest

    # steps are the commands that will be executed on the runner
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # runs a single command using the runners shell
      - name: Run one line script
        run: echo Hello, world!
      
      # then run this next step after the last one has completed
      - name: second step
        run: |
          echo second step
          echo second step part 2
  
  build-db:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Runs DB aetup
        run: echo run next job for db setup
  
  packaging:
    runs-on: self-hosted # this will run on a self-hosted runner on my local machine
    needs: [build-app, build-db]
