name: 'custom ENV'

on:  workflow_dispatch

env:
  DAY: 'Monday'
  testvar: 'test'

jobs:
  mainjob:
    name: prints vars
    runs-on: ubuntu-latest 
    env:
      local: 'local'
      testvar: 'test2'
    steps:
      - name: prints all vars
        env:
          testvar: 'test3'
        run: |
          echo "all vars"
          env
          echo "local var ${{ ENV.local }}"
          echo "testvar var ${{ ENV.testvar }}"
          echo "day var ${{ ENV.DAY }}"

      - name: prints all vars p2
        run: |
          echo "testvar var ${{ ENV.testvar }}"
  
  job2:
    name: prints testvar
    runs-on: ubuntu-latest 
    steps:
      - name: prints testvar
        run:  echo "testvar var ${{ ENV.testvar }}"
  
  job3:
    name: save var
    runs-on: ubuntu-latest 
    steps:
      - name: save action_state
        run:  echo "action_state=yellow" >> $GITHUB_ENV
  
      - name: prints action_state
        run:  echo "action_state var ${{ ENV.action_state }}"
  
  ubuntu-var-print:
    name: prints ubuntu var
    runs-on: ubuntu-latest 
    steps:
      - name: prints ubuntu var
        run:  env
  windows-var-print:
    name: prints windows var
    runs-on: windows-latest 
    steps:
      - name: prints windows var
        run:  env
  macos-var-print:
    name: prints macos var
    runs-on: macos-latest 
    steps:
      - name: prints macos var
        run:  env